### ISSUE TITLE
Admin should be able to see all courses

### ISSUE THREAD

**Issue by ChrisXJH** [follothru/follothru-backend#41]
**Description**
Currently the admins can only see their own courses, which makes it impossible for admin to approve other pending courses. 

**Expected behaviour:**
Admin should be able to see and approve all courses.

**Comment by andythsu** [comment]
do you want me to create another endpoint to get all unapproved courses?

**Comment by andythsu** [comment]
or append the result on the old endpoint?

**Comment by ChrisXJH** [comment]
> do you want me to create another endpoint to get all unapproved courses?

You can just modify the existing one to return all courses if the current user is admin

**Comment by andythsu** [comment]
> > do you want me to create another endpoint to get all unapproved courses?
> 
> You can just modify the existing one to return all courses if the current user is admin

ok

**Comment by andythsu** [comment]
> > > do you want me to create another endpoint to get all unapproved courses?
> > 
> > 
> > You can just modify the existing one to return all courses if the current user is admin
> 
> ok

can super admin see all courses too?

**Comment by ChrisXJH** [comment]
> > > > do you want me to create another endpoint to get all unapproved courses?
> > > 
> > > 
> > > You can just modify the existing one to return all courses if the current user is admin
> > 
> > 
> > ok
> 
> can super admin see all courses too?

Yes, I believe it is the current behaviour.
