### ISSUE TITLE
Library for sending HTML/text emails

### ISSUE THREAD

**Issue by ChrisXJH** [follothru/follothru-backend#51]
**Description**
Library for sending HTML/text email to specified users.

**Comment by ChrisXJH** [comment]
https://www.youtube.com/watch?v=9zPZ9yJML6E&list=WL

**Comment by andythsu** [comment]
1. npm install --save handlebars nodemailer email-templates bluebird
2. require('nodemailer')
3. require('email-templates').EmailTemplate
4. create a transporter
5. send email using EmailTemplate

**Comment by andythsu** [comment]
1. get reminders to be sent
2. get recipient id
3. end point is GET /email/sendEmail

**Comment by ChrisXJH** [comment]
Sending emails is an internal task. There's no need to expose endpoints.

**Comment by andythsu** [comment]
we can create a separate independent module for sending email (in this case it is independent from email service) rather than giving its own endpoint

**Comment by ChrisXJH** [comment]
GET might not be appropriate for sendEmail. Use something like POST or PUT?
